
title = "A few places you can find Golang remote jobs"
author =  "Øyvind Gerrard Skaar" 
subtitle = ""
date = 2016-04-15
servepath = "go-remote-jobs"
published =  true
tags = [ "foo", "bar", "go", "golang", "javascript" ]

thisformatversion = 1
