
title = "Too many tools and frameworks3"
subtitle = "The definitive guide to the javascript tooling landscape in 2015"
author = "Adam Morse"
date = 2015-06-27

servepath = "test-1"
published =  true
tags = [ "foo", "bar", "go", "golang", "javascript" ]

thisformatversion = 1
