
title = "Prototyping with NoCode and AI tools"
author =  "Øyvind Gerrard Skaar" 
blogsubtitle = "trying out lots of different No-code and AI tools"
date = 2024-04-10
servepath = "nocode-and-ai-tools-for-prototyping"
published =  true
tags = [ "mpv", "prototyping", "nocode" ]

thisformatversion = 1
